### ISSUE TITLE
Error appears while installation

### ISSUE THREAD

**Issue by iskhakov** [korablin/simpleANN#1]
```
$ python simpleANN.py
Traceback (most recent call last):
  File "simpleANN.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/Users/iiskhako/github/simpleANN/venv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/iiskhako/github/simpleANN/venv/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/iiskhako/github/simpleANN/venv/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 19, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.```

**Comment by iskhakov** [comment]
Create a file ~/.matplotlib/matplotlibrc there and add the following code: backend: TkAgg
